# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 31fc1a08ff5a6fe836cadab9fba652fcc6e40e85167760104bbec1138c3cfd11a5d2311514c6e4053871a8ca2a0d2f4a26d4e0fe24937dfd18c342b92fd227e8

test:
  secret_key_base: b7023bb50ec89b074c5303fae1bf35141dfaa8681aac9b4bd83d6ff7616779c4492ea1c447fb01e17fb61c2b91bc41d96a67555f294d3cba640cf68fb9ff5ba2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
